dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy3"
matrix:
  include:
  - python: 3.7
    dist: xenial
  - python: 3.8
    dist: xenial
  - python: pypy
    dist: xenial
  - python: pypy3
    dist: xenial
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install -r requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; pip install coveralls; fi
script: if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coverage run --source=aliyun setup.py test; else python setup.py test; fi
after_success: if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coveralls; fi
deploy:
  provider: pypi
  user: joamag
  password:
    secure: 0srn6cyZQcESzOQF9b6wsKEO1xmXNQ3YWV3yE3fPYrjywPOrzzKouxsuCRHp5IFm+nxIcKE4NchHiNUIi1EA/TsevLJRDbmq6BZqN1J+xMjUSJ9soEUcMRdH11jfdW6d2eCEmxzcPbBWYOj1fY0HLfPpSbF2wlMQl5ZfF/y9mxu2wQm5NxCz4NCMRuksrmycIbSIz1BZgpH2uEuGvxFL+a0WQWwx5/mTpITvloThsOIDN3tLU+I2ufc7MBPP+LDJJej0vcDb55fEyt3gN1ac+9OT0GRk3tyQpFtVZSdb0x9+ZN3R2yhr+22FgIMpXARzxSO2lEYbATxY9eFjSw4RBvfKn05s0a0N8/1lG5rORRZTeoY7ZbDEegPgvGbyAoxZAuu5Ae2hGNDkMAS2t+2WkFf5N4Gcyvd3ys7Af2skO9ii6Sx1pivQS1IN9j1wBNT1bTcoq51rAcE1C5AtJ4DE3iVulu/JYBmhyszjsf03FyGvXYF2VPrztGrGElUiekjkS2HKIugNiajy8HioKcuutWroEQnMOhfE6V2cfP/O79vxoteUtXbSAnxOj/pfNU4K1rEKJ4+XQPnn2dAINiXEAQkFWp9stiu56Nr227LrMFlH6paPyLRpyMyPyjz780UKqecU4qa23nly860KT2ysYdstC9phXBavTDSNYZpPk1Y=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
